name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Clasp
        run: sudo npm install -g @google/clasp

      - name: Create clasprc.json and .clasp.json
        run: |
          mkdir -p ~/.clasprc.json
          rm -rf ~/.clasprc.json
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
          echo '{"scriptId":"${{ secrets.CLASPRC_SCRIPT_ID }}","rootDir":"./"}' > ./.clasp.json

      - name: Push Code to Apps Script
        run: clasp push --force
